version: '3'
services:
  php-web-server:
    image: nginx:latest
    container_name: php-web-server
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./app:/app
    depends_on:
      - php
      - mysql-php
      - phpMyAdmin
  php:
    # image: php:fpm
    build:
      context: .
      dockerfile: PHP.Dockerfile
      args:
        USER: kaungminkhant
    container_name: php-interpreter
    expose:
      - 9000
    volumes:
      - ./app:/app
  mysql-php:
    image: mariadb:latest
    container_name: mysql-php
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test
    volumes:
      - mysql-php-data:/var/lib/mysql
    expose:
      - 3306
  phpMyAdmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpMyAdmin
    environment:
      PMA_HOST: mysql-php
      PMA_PORT: 3306
      PMA_ABSOLUTE_URI: http://127.0.0.1/phpmyadmin/
    expose:
      - 80
    depends_on:
      - mysql-php

volumes:
  mysql-php-data: {}